#!/bin/bash

# setup.sh
# Interactive setup script for free-oci-k8s project.

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${BLUE}==========================================${NC}"
echo -e "${GREEN}    Oracle Cloud Free K8S Setup Wizard    ${NC}"
echo -e "${BLUE}==========================================${NC}"
echo -e "This script will help you configure your Always-Free Kubernetes cluster."
echo ""

# 1. Core OCI Configuration
echo -e "${YELLOW}[1/4] Core OCI Configuration${NC}"
read -p "Enter OCI Region (e.g., us-phoenix-1): " REGION
read -p "Enter Regional Identifier (e.g., PHX, ASH, FRA): " REGION_ID
read -p "Enter Compartment OCID: " COMPARTMENT_OCID

# Basic OCID validation
if [[ ! $COMPARTMENT_OCID =~ ^ocid1\.compartment\.oc1\. ]]; then
    echo -e "${RED}Warning: That doesn't look like a valid compartment OCID.${NC}"
fi

read -p "Enter Kubernetes Version (default v1.34.2): " K8S_VERSION
K8S_VERSION=${K8S_VERSION:-v1.34.2}

read -p "Enter Cluster Name (default cluster1): " CLUSTER_NAME
CLUSTER_NAME=${CLUSTER_NAME:-cluster1}

echo -e "${BLUE}Note: To find your Image OCID, run:${NC}"
echo "oci compute image list --compartment-id \$COMPARTMENT_OCID --query \"data[?contains(display_name, 'Oracle-Linux-9')].{id:id,name:display_name}\" --output table"
read -p "Enter Image OCID for worker nodes: " IMAGE_ID
echo ""

# 2. Security Configuration
echo -e "${YELLOW}[2/4] Security Configuration${NC}"
read -p "Enable public access to Kubernetes API? (y/N): " PUBLIC_API
if [[ "$PUBLIC_API" =~ ^[Yy]$ ]]; then
    K8S_API_PUBLIC="true"
    read -p "Enter allowed CIDR blocks (comma separated, e.g., 1.2.3.4/32,5.6.7.8/24): " API_CIDRS
    if [ -z "$API_CIDRS" ]; then
        API_CIDRS_HCL="[]"
    else
        API_CIDRS_HCL=$(echo $API_CIDRS | sed 's/ //g' | sed 's/,/","/g' | sed 's/^/["/' | sed 's/$/"]/')
    fi
    CREATE_BASTION="false"
    BASTION_CIDRS_HCL="[]"
    CREATE_VPN="false"
    CPE_IP=""
    CUSTOMER_CIDR=""
else
    K8S_API_PUBLIC="false"
    API_CIDRS_HCL="[]"
    echo -e "${BLUE}API is private. Choose access method:${NC}"
    
    read -p "  Enable OCI Bastion Service? (Y/n): " BASTION
    BASTION=${BASTION:-Y}
    if [[ "$BASTION" =~ ^[Yy]$ ]]; then
        CREATE_BASTION="true"
        read -p "  Enter bastion allowed CIDRs (comma separated, default 0.0.0.0/0): " BASTION_CIDRS
        if [ -z "$BASTION_CIDRS" ]; then
            BASTION_CIDRS_HCL="[\"0.0.0.0/0\"]"
        else
            BASTION_CIDRS_HCL=$(echo $BASTION_CIDRS | sed 's/ //g' | sed 's/,/","/g' | sed 's/^/["/' | sed 's/$/"]/')
        fi
    else
        CREATE_BASTION="false"
        BASTION_CIDRS_HCL="[]"
    fi

    read -p "  Enable Site-to-Site VPN? (y/N): " VPN
    if [[ "$VPN" =~ ^[Yy]$ ]]; then
        CREATE_VPN="true"
        read -p "    Enter VPN CPE Public IP: " CPE_IP
        read -p "    Enter Customer Network CIDR (e.g., 192.168.0.0/16): " CUSTOMER_CIDR
    else
        CREATE_VPN="false"
        CPE_IP=""
        CUSTOMER_CIDR=""
    fi
fi

# Generate terraform.tfvars
cat <<EOF > terraform.tfvars
# Generated by setup.sh
region            = "${REGION}"
region_identifier = "${REGION_ID}"
compartment_ocid  = "${COMPARTMENT_OCID}"
kubernetes_version = "${K8S_VERSION}"
image_id          = "${IMAGE_ID}"
cluster_name      = "${CLUSTER_NAME}"

# Security Configuration
kubernetes_api_public_enabled = ${K8S_API_PUBLIC}
allowed_k8s_api_cidrs         = ${API_CIDRS_HCL}
create_bastion                = ${CREATE_BASTION}
bastion_client_cidr_allow_list = ${BASTION_CIDRS_HCL}
create_vpn                    = ${CREATE_VPN}
cpe_ip_address                = "${CPE_IP}"
customer_network_cidr         = "${CUSTOMER_CIDR}"

# Node Pool
node_pool_size                = 4
EOF

echo -e "${GREEN}✓ Created terraform.tfvars${NC}"
echo ""

# 3. Remote Backend Configuration
echo -e "${YELLOW}[3/4] Remote Backend Configuration (Optional)${NC}"
read -p "Do you want to use OCI Object Storage for remote state? (y/N): " USE_BACKEND

if [[ "$USE_BACKEND" =~ ^[Yy]$ ]]; then
    echo -e "${BLUE}Tip: To generate these via OCI CLI, run:${NC}"
    echo -e "USER_ID=\$(oci iam user get --user-id <your-user-ocid> --query \"data.id\" --output string)"
    echo -e "oci iam customer-secret-key create --user-id \$USER_ID --display-name \"terraform-backend\""
    echo ""
    read -p "Enter Object Storage Namespace: " NAMESPACE
    read -p "Enter Bucket Name: " BUCKET
    read -p "Enter S3 Access Key ID: " ACCESS_KEY
    read -s -p "Enter S3 Secret Key: " SECRET_KEY
    echo ""

    # Create .terraform.env
    cat <<EOF > .terraform.env
export AWS_ACCESS_KEY_ID="${ACCESS_KEY}"
export AWS_SECRET_ACCESS_KEY="${SECRET_KEY}"
export AWS_DEFAULT_REGION="${REGION}"
EOF

    # Create backend.tf
    cat <<EOF > backend.tf
terraform {
  backend "s3" {
    bucket   = "${BUCKET}"
    key      = "terraform.tfstate"
    region   = "${REGION}"
    endpoint = "https://${NAMESPACE}.compat.objectstorage.${REGION}.oraclecloud.com"

    skip_region_validation      = true
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    force_path_style            = true
  }
}
EOF
    echo -e "${GREEN}✓ Created backend.tf and .terraform.env${NC}"
else
    echo -e "${BLUE}Skipping remote backend. Local state will be used.${NC}"
fi
echo ""

# 4. Initialization
echo -e "${YELLOW}[4/4] Initialization${NC}"
read -p "Do you want to run 'terraform init' now? (y/N): " RUN_INIT

if [[ "$RUN_INIT" =~ ^[Yy]$ ]]; then
    if [ -f .terraform.env ]; then
        source .terraform.env
    fi
    terraform init
    echo -e "${GREEN}✓ Terraform initialized successfully!${NC}"
else
    echo -e "You can initialize later by running 'terraform init'."
fi

echo -e "\n${GREEN}==========================================${NC}"
echo -e "${GREEN}         Setup Complete!                  ${NC}"
echo -e "${GREEN}==========================================${NC}"
echo -e "Next steps:"
if [ -f .terraform.env ]; then
    echo -e "1. Run: ${CYAN}source .terraform.env${NC}"
fi
echo -e "2. Review ${CYAN}terraform.tfvars${NC}"
echo -e "3. Run: ${CYAN}terraform plan${NC}"
echo -e "4. Run: ${CYAN}terraform apply${NC}"
echo -e "${GREEN}==========================================${NC}"
